use crate::setup::lua::{Build, DepStyle, Rule};

fn ninja_escape(mut str: String) -> String {
    str = str.replace("$", "$$");
    str = str.replace(" ", "$ ");
    str = str.replace(":", "$:");
    str = str.replace("\n", "$\n");
    str
}

pub fn build_ninja_file(rules: &Vec<Rule>, builds: &Vec<Build>) -> String {
    let mut ninja_data = String::new();

    ninja_data.push_str("# Generated by Fabricate\n");

    ninja_data.push_str("ninja_required_version = 1.9.0\n\n");

    ninja_data.push_str("# Rules\n");
    for rule in rules {
        ninja_data.push_str(format!("rule {}\n", ninja_escape(rule.name.clone())).as_str());
        ninja_data.push_str(format!("    command = {}\n", rule.command.clone()).as_str());

        if let Some(description) = rule.description.as_ref() {
            ninja_data.push_str(format!("    description = {}\n", ninja_escape(description.clone())).as_str());
        }

        match rule.depstyle {
            DepStyle::Normal => {}
            DepStyle::Gcc => ninja_data.push_str("    deps = gcc\n"),
            DepStyle::Msvc => ninja_data.push_str("    deps = msvc\n"),
        };

        ninja_data.push('\n');
    }

    ninja_data.push_str("# Build Statements\n");
    for build in builds {
        let output = ninja_escape(build.output.to_string_lossy().to_string());
        let inputs: Vec<String> = build.input.iter().map(|i| ninja_escape(i.to_string_lossy().to_string())).collect();
        ninja_data.push_str(format!("build {}: {} {}", output, build.rule, inputs.join(" ")).as_str());

        if let Some(implicit_inputs) = build.implicit_inputs.as_ref() {
            let implicit_inputs: Vec<String> = implicit_inputs.iter().map(|i| ninja_escape(i.to_string_lossy().to_string())).collect();
            ninja_data.push_str(format!(" | {}", implicit_inputs.join(" ")).as_str());
        }
        ninja_data.push('\n');

        for (k, v) in build.variables.iter() {
            ninja_data.push_str(format!("    {} = {}\n", k, ninja_escape(v.clone())).as_str());
        }

        ninja_data.push('\n');
    }

    return ninja_data;
}
