--- @meta

--- @class (exact) Source
--- @field path string Relative (to the build directory) path to the source file.
Source = {}

--- @class (exact) Artifact
--- @field path string Relative (to the build directory) path to the artifact.
Artifact = {}

--- @class (exact) Rule
--- @field name string Rule name (unique).
Rule = {}

--- Define a build of the rule.
--- @param output string The unique name of the artifact generated by this build.
--- @param input (Source | Artifact)[] Inputs.
--- @param variables { [string]: string } The variable values.
--- @param implicit_inputs (Source | Artifact)[]? Implicit inputs.
--- @return Artifact
function Rule:build(output, input, variables, implicit_inputs) end
