--- @meta

--- @class (exact) Source
--- @field rel_path string Relative (to the project root) path to the source file.
--- @field abs_path string Absolute path to the source file.
Source = {}

--- @class (exact) Rule
--- @field name string Rule name (unique).
Rule = {}

--- Define a build of the rule.
--- @param output string The filename or path (relative to the output dir) of the artifact generated by this build.
--- @param input (Source | Artifact)[] Inputs.
--- @param variables { [string]: string } The variable values.
--- @param implicitInputs (Source | Artifact)[]? Implicit inputs.
--- @return Artifact
function Rule:build(output, input, variables, implicitInputs) end

--- @class (exact) Executable
--- @field name string Filename of the executable.
--- @field path string Absolute path to the executable.
Executable = {}

--- Invoke the executable with given arguments.
--- WARNING: This will throw a lua error if the invocation fails.
--- @vararg string
--- @return string stdout
function Executable:invoke(...) end

--- @class (exact) Artifact
--- @field rel_path string Relative (to the build directory) path to the artifact.
--- @field abs_path string Absolute path to the artifact.
Artifact = {}
