use std::{
    collections::HashMap,
    env,
    fs::{create_dir_all, read, write},
    path::{Path, PathBuf},
    process::exit,
};

use anyhow::{anyhow, bail, Context, Result};
use clap::{Args, Parser, Subcommand};
use colog::format::CologStyle;
use compiler::Compiler;
use dependency::Dependency;
use executable::Executable;
use glob::glob;
use include_dir::IncludeDirectory;
use json::JsonValue;
use linker::Linker;
use log::{error, warn};
use mlua::{ExternalResult, IntoLua, Lua, Value, Variadic};
use ninja_writer::Ninja;
use source::Source;

mod compiler;
mod dependency;
mod executable;
mod include_dir;
mod linker;
mod object;
mod source;

#[derive(Parser)]
#[command(version, next_line_help = true)]
struct FabOptions {
    #[arg(long, help = "config file path", default_value = "fab.lua")]
    config: String,

    #[command(subcommand)]
    command: MainCommand,
}

#[derive(Subcommand)]
enum MainCommand {
    #[command(about = "configure build")]
    Configure(ConfigureOptions),
}

#[derive(Args)]
struct ConfigureOptions {
    #[arg(short = 'D', long = "option", help = "pass user defined option", value_parser = keyvalue_opt_validate)]
    options: Vec<(String, String)>,

    #[arg(long = "prefix", help = "prefix", default_value = "/usr/local")]
    prefix: String,

    #[arg(help = "path to build directory", default_value = "build")]
    builddir: String,
}

struct FabLuaContext {
    options: HashMap<String, String>,
    project_root: PathBuf,
    build_cache: PathBuf,

    ninja: Ninja,
    compile_commands: Vec<JsonValue>,

    rule_cache: Vec<String>,
    dependency_cache: Vec<String>,
}

struct FabLogStyle;

impl CologStyle for FabLogStyle {
    fn prefix_token(&self, level: &log::Level) -> String {
        format!("{} >> ", self.level_color(level, self.level_token(level)))
    }

    fn level_token(&self, level: &log::Level) -> &str {
        match *level {
            log::Level::Error => "Error",
            log::Level::Warn => "Warning",
            log::Level::Info => "Info",
            log::Level::Debug => "Debug",
            log::Level::Trace => "Trace",
        }
    }
}

const BUILTINS_FAB: &'static str = include_str!("lua/builtins.fab.lua");
const BUILTINS_GENERAL: &'static str = include_str!("lua/builtins.general.lua");

fn keyvalue_opt_validate(s: &str) -> Result<(String, String), String> {
    match s.split_once("=") {
        None => Err(format!("`{s}` is not a key value pair")),
        Some((key, value)) => Ok((key.to_string(), value.to_string())),
    }
}

impl FabLuaContext {
    fn path_dependencies(&self) -> PathBuf {
        self.build_cache.join("dependencies")
    }
}

fn main() {
    colog::default_builder().format(colog::formatter(FabLogStyle)).init();

    if let Err(err) = run_main() {
        error!("{}", err);
        if err.chain().len() > 1 {
            error!("Caused by:");
            for (i, sub_error) in err.chain().skip(1).enumerate() {
                error!("  {}: {}", i, sub_error)
            }
        }

        exit(1);
    }
}

fn run_main() -> Result<()> {
    let cli_options = FabOptions::parse();

    match cli_options.command {
        MainCommand::Configure(configure_options) => {
            let config_path = Path::new(&cli_options.config).canonicalize()?;

            create_dir_all(&configure_options.builddir)?;
            let build_cache = Path::new(&configure_options.builddir).canonicalize()?;

            let project_root = match config_path.parent() {
                None => bail!("Failed to resolve config directory"),
                Some(config_dir) => {
                    env::set_current_dir(config_dir)?;
                    config_dir.to_owned()
                }
            };

            // Setup fab context
            let mut options: HashMap<String, String> = HashMap::new();
            for (key, value) in configure_options.options {
                options.insert(key, value);
            }

            let lua_context = FabLuaContext {
                options,
                project_root,
                build_cache: build_cache.clone(),
                ninja: Ninja::new(),
                compile_commands: Vec::new(),
                rule_cache: Vec::new(),
                dependency_cache: Vec::new(),
            };

            // Create build cache
            create_dir_all(&build_cache)?;
            create_dir_all(&build_cache.join("objects"))?;
            create_dir_all(&build_cache.join("depfiles"))?;
            create_dir_all(lua_context.path_dependencies())?;

            write(build_cache.join(".gitignore"), "# Generated by Fab.\n*")?;

            // Execute build script
            let lua = match setup_lua(lua_context) {
                Ok(lua) => lua,
                Err(err) => return Err(anyhow!(err.to_string()).context("Failed to setup lua")),
            };

            if let Err(err) = lua.load(read(config_path)?).set_name(format!("@{}", &cli_options.config)).exec() {
                return Err(anyhow!(err.to_string()).context("Failed to run config"));
            }

            // Write ninja build
            let lua_context = lua.app_data_mut::<FabLuaContext>().unwrap();
            let ninja_config = lua_context.ninja.to_string();
            write(build_cache.join("build.ninja"), ninja_config)?;
            write(build_cache.join("compile_commands.json"), JsonValue::Array(lua_context.compile_commands.clone()).pretty(4))?;

            let mut config_table = toml::Table::new();
            config_table.insert("prefix".to_string(), toml::Value::String(configure_options.prefix.clone()));
            config_table.insert("builddir".to_string(), toml::Value::String(configure_options.builddir.clone()));
            write(build_cache.join("fab.config.toml"), toml::to_string(&config_table)?)?;
        }
    }

    Ok(())
}

fn setup_lua(lua_context: FabLuaContext) -> mlua::Result<Lua> {
    let lua = Lua::new();

    // Setup fab table
    let fab_table = lua.create_table()?;

    fab_table.set("find_executable", lua.create_function(Executable::find)?)?;

    fab_table.set(
        "glob",
        lua.create_function(|_: &Lua, pattern: String| {
            let mut paths: Vec<PathBuf> = Vec::new();
            for entry in glob(&pattern).with_context(|| format!("Glob pattern `{}` failed", pattern)).into_lua_err()? {
                match entry {
                    Ok(path) => paths.push(path),
                    Err(_) => continue,
                }
            }
            Ok(paths)
        })?,
    )?;

    fab_table.set(
        "option",
        lua.create_function(|lua: &Lua, (name, default): (String, Value)| {
            let fab_context = lua.app_data_ref::<FabLuaContext>().unwrap();

            if !fab_context.options.contains_key(&name) {
                return Ok(default);
            }

            Ok(fab_context.options[&name].clone().into_lua(lua)?)
        })?,
    )?;

    fab_table.set(
        "project_root",
        lua.create_function(|lua: &Lua, _: ()| Ok(lua.app_data_ref::<FabLuaContext>().unwrap().project_root.clone()))?,
    )?;

    fab_table.set("create_compiler", lua.create_function(Compiler::create)?)?;
    fab_table.set("create_linker", lua.create_function(Linker::create)?)?;
    fab_table.set("dependency", lua.create_function(Dependency::create)?)?;
    fab_table.set("source", lua.create_function(Source::create)?)?;
    fab_table.set("include_directory", lua.create_function(IncludeDirectory::create)?)?;

    // Globals
    lua.globals().set("fab", fab_table)?;

    lua.globals().set(
        "path",
        lua.create_function(|_: &Lua, (base, parts): (PathBuf, Variadic<PathBuf>)| {
            let mut path = base;
            for part in parts {
                path = path.join(part);
            }
            Ok(path)
        })?,
    )?;

    lua.globals()
        .set("panic", lua.create_function(|_: &Lua, message: String| -> mlua::Result<()> { panic!("{}", message) })?)?;

    lua.globals().set(
        "warn",
        lua.create_function(|_: &Lua, message: String| {
            warn!("{}", message);
            Ok(())
        })?,
    )?;

    lua.set_app_data(lua_context);
    lua.load(BUILTINS_FAB).set_name("=builtins.fab").exec()?;
    lua.load(BUILTINS_GENERAL).set_name("=builtins.general").exec()?;

    Ok(lua)
}
